---
title: Assignment 1
output:
  md_document:
    variant: markdown_github
---
###### b06901048 電機五 陳昱行
## Problem1
### i.
```{r}
col.name <- c('Party', 'Results 2019 (%)', 'Results 2014 (%)')
Party <- c('ANC', 'DA',
'EFF','IFP','FF Plus','Others')
Results_2019 <- c(57.50,20.77,10.80,3.38,2.38,5.17)
Results_2014 <- c(62.15,22.23,6.35,2.40,0.90,5.97)
dat <- data.frame(Party,Results_2019,Results_2014)
names(dat) <- col.name
library(knitr)
kable(dat[1:6,])
summary(dat)
```

### ii.
```{r}
dat.plot <- matrix(c(Results_2019,Results_2014),nrow=2,ncol=6,byrow=T)
# quartz()
b <- barplot(dat.plot,names.arg=Party,beside=T,ylim=c(0,65))
text(x = b, y=dat.plot, label=dat.plot,pos = 3, cex = 0.8,offset=0.1)
```

## Problem2

### i.

```{r}
time.until.score <- c(53,49,42,26,6,39,60,10,47,2,38,74,18,52,29,11,24,21,57,42,37,17,12,18, 77,25,30,2,84,20,47,15,31,11,27,95,68,42,20,15,75,27,8,31,5,4,60,30,2)
table(time.until.score)
F.head <- ecdf(time.until.score)
print(c(F.head(30),F.head(45),F.head(60)))
```

### ii.

```{r}
f.head <- density(time.until.score, kernel="rectangular",bw = 10)
# n is default to 512
print(c(f.head$y[sum(f.head$x <=30)],f.head$y[sum(f.head$x <=45)],f.head$y[sum(f.head$x <=60)]))
```

### iii.

```{r}
mean(time.until.score)
median(time.until.score)
quantile(time.until.score,c(0.75,0.25))
```

### iv.
```{r}
#interquantile range
quantiles <- quantile(time.until.score,c(0.75,0.25))
unname(quantiles[1] - quantiles[2])
#variance
var(time.until.score)
```

### v.
```{r}
hist(time.until.score,xlab="Time until score",main = paste("Histogram of" , "Time until score"))
plot.ecdf(time.until.score)
plot(f.head,main=paste("rectangular kernel desity plot"))
boxplot(time.until.score)
```

## Problem 3

### i.

```{r}
pizza <- read.csv('http://chris.userweb.mwn.de/book/pizza_delivery.csv',
                  stringsAsFactors = T)
summary(pizza[c('time','temperature','bill','pizzas')])
```

### ii.

```{r}
quantile(pizza$time,0.99)
quantile(pizza$temperature,0.99)
```


### iii.

```{r}
mean(abs(pizza$temperature - mean(pizza$temperature)))
mad(pizza$temperature,constant=1)
```

### iv.

```{r}
mean(scale(pizza$time))
# variance is a matrix
var(scale(pizza$time))[1]
```

### v.

```{r}
boxplot(pizza$time,outline=FALSE)
```

### vi.

```{r}
plot(pizza$time,pizza$temperature)
cor(pizza$time,pizza$temperature, method = 'pearson')
cor(pizza$time,pizza$temperature, method = 'spearman')
```

## Problem4
```{r}
passenger.classes <- c('first','second','third','staff')
passenger <- c(337,285,721,885)
passenger.rescued <- c(135,160,541,674)
passenger.unrescued <- passenger - passenger.rescued
```

### i.

```{r}
table.contigency <-matrix(c(passenger.rescued,passenger.unrescued),nrow=2,ncol=4,byrow=T)
dimnames(table.contigency) <- list(c('rescued','unrescued'),passenger.classes)
table.contigency.addmargin <- addmargins(table.contigency)
print(table.contigency.addmargin)
```

### ii.

```{r}
expected.absolute.frequency <- NULL
n <- table.contigency.addmargin['Sum','Sum']
for(i in table.contigency.addmargin['Sum',]){
    expected.absolute.frequency <- c(expected.absolute.frequency,i*table.contigency.addmargin['rescued','Sum']/n)
}
print(expected.absolute.frequency)
```

### iii.

```{r}
min.k.l <- min(dim(table.contigency))
chi <- chisq.test(table.contigency)$statistic
Cramers.V <-sqrt(chi/(table.contigency.addmargin['Sum','Sum']*(min.k.l-1)))
print(paste("χ2 = ",chi,"Cramer's V = ",Cramers.V))
```

### iv.

```{r}
concordant.K <- 0
decordant.D <- 0
rev.table.contigency <- matrix(rev(table.contigency),nrow=2,ncol=4)
print(rev.table.contigency)
#calculate concordant
for( i in seq(1,dim(rev.table.contigency)[2]-1)){
    for(j in seq(i+1,dim(rev.table.contigency)[2])){
        concordant.K <- concordant.K + rev.table.contigency[1,i] * rev.table.contigency[2,j]
    }
}
#calculate decordant
for( i in seq(dim(rev.table.contigency)[2],2)){
    for(j in seq(i-1,1)){
        decordant.D <- decordant.D + rev.table.contigency[1,i] * rev.table.contigency[2,j]
    }
}
n <- table.contigency.addmargin['Sum','Sum']
print(paste("γ = ",(concordant.K-decordant.D)/(concordant.K+decordant.D),"τc = ",2*min(dim(rev.table.contigency))*(concordant.K-decordant.D)/(n^2*min.k.l-1)))
```

### v.

```{r}
new.class <- c('Class A','Class B')
new.rescued <- c(135+160,541+674)
new.total <- c(337+285,721+885)
new.unrescued <- new.total - new.rescued
new.contingency.table <- matrix(c(new.rescued,new.unrescued),nrow=2,ncol=2)
dimnames(new.contingency.table) <- list(c('rescued','unrecued'),new.class)
new.contingency.table.addmargin <- addmargins(new.contingency.table)
print(new.contingency.table.addmargin)
new.chi <- chisq.test(new.contingency.table)$statistic
new.min.k.l <- min(dim(new.contingency.table))
new.Cramers.V <- sqrt(new.chi/(new.contingency.table.addmargin['Sum','Sum']*(new.min.k.l-1)))
print(paste("χ2 = ",new.chi,"Cramer's V = ",new.Cramers.V))
risk.new.unrescued.classB <-new.contingency.table.addmargin[2,2]/new.contingency.table.addmargin[2,3]
risk.new.unrescued.classA <-new.contingency.table.addmargin[1,2]/new.contingency.table.addmargin[1,3]
relative.risk <- risk.new.unrescued.classB/risk.new.unrescued.classA
relative.not.risk <- (1-risk.new.unrescued.classB)/(1-risk.new.unrescued.classA)
print(paste("relative risks = ",relative.risk, "odds ratio = ",relative.risk/relative.not.risk))
```
